### ISSUE TITLE
Fix status checks

### ISSUE THREAD

**Issue by dankolbman** [d3b-center/bixtools#48]
It would appear that the dockercloud status check has been failing for some time.
We should ensure that all CI checks are passing and heeded. If the check is no longer valid, perhaps it should be removed.

**Comment by migbro** [comment]
Yeah - this check never has seemed to work. I'm not sure how/when it was implemented, but 99% of the files, if you were on the dockerhub side, and you triggered a build, would build just fine.

**Comment by dankolbman** [comment]
Can we remove it then?

**Comment by migbro** [comment]
Yes please, I'd say remove the current CI implementation on this repo since it does not work.

**Comment by migbro** [comment]
I think this is no longer relevant
