### ISSUE TITLE
Publish images to github

### ISSUE THREAD

**Issue by dankolbman** [d3b-center/bixtools#49]
Now that GitHub offers package repositories for docker images, it would be nice if we could add some CI work to publish these packages to it upon merges to master.

**Comment by migbro** [comment]
Yeah, that needs some work.  We had some hooks, but the problem is that since they are all in the same repo, dockerhub would try re-build every single one, and on occasion, due to an unforeseen availability, or change in end point, it would break the image.  Definitely open to suggestions.

**Comment by migbro** [comment]
We have a CI and it publishes to seven bridges docker registry.
